SiteName : test
RunMode : debug
Server:
  Https : false
  HttpPort : 8080
  ReadTimeout : 60000000000  #60s
  WriteTimeout : 60000000000

Database:
  Type : mysql
  User : root
  Password : 123
  Host : 127.0.0.1:3306
  Name : test
